package com.harium.suneidesis.bui.input;

public enum InputAction {

    PRESS, TYPE, RELEASE,
    MOUSE_CLICK, MOUSE_PRESSED, MOUSE_RELEASED, MOUSE_MOVE, MOUSE_MOVE_RELATIVE,
    ACTIVATE_WINDOW, MINIMIZE_WINDOW, CLOSE_WINDOW,
    RUN_COMMAND, WAIT

}
